"use client";
import { useEffect, useMemo, useState } from "react";

type Assignment={scheduled_at:string|null;duration_minutes:number;interviewer_names:string[];room:string|null;mode:"offline"|"online"};
type Row={id:string;applicant_code:string;name:string;major:string|null;interview_availability:string|null;final_status:string;assignment:Assignment|null;hermes_ready:boolean;review_count:number;minimum_review_count:number;review_shortage:boolean;interview_average:number|null;interview_min:number|null;interview_max:number|null;high_variance:boolean};
function localInput(value:string|null){if(!value)return "";const date=new Date(value);const offset=date.getTimezoneOffset()*60000;return new Date(date.getTime()-offset).toISOString().slice(0,16);}

export default function InterviewsClient(){
 const [rows,setRows]=useState<Row[]>([]);const [reviewerId,setReviewerId]=useState("");const [reviewerName,setReviewerName]=useState("");const [loading,setLoading]=useState(true);const [message,setMessage]=useState("");const [filter,setFilter]=useState("all");const recruitmentId=process.env.NEXT_PUBLIC_RECRUITMENT_ID??"";
 async function load(){setLoading(true);const response=await fetch(`/api/interviews/summary?recruitmentId=${encodeURIComponent(recruitmentId)}`);const data=await response.json();if(!response.ok)throw new Error(data.error??"면접 현황 조회 실패");setRows(data.rows??[]);setLoading(false);}
 useEffect(()=>{const id=localStorage.getItem("coffeeright.reviewerId");const name=localStorage.getItem("coffeeright.reviewerName");if(!id||!name){location.href="/reviewer";return;}setReviewerId(id);setReviewerName(name);load().catch(e=>{setLoading(false);setMessage(e.message)});},[]);
 const visible=useMemo(()=>rows.filter(row=>filter==="unscheduled"?!row.assignment?.scheduled_at:filter==="shortage"?row.review_shortage:filter==="variance"?row.high_variance:true),[rows,filter]);
 async function saveSchedule(row:Row, scheduledAt:string, room:string, interviewers:string){const response=await fetch(`/api/interviews/${row.id}`,{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({action:"schedule",reviewerId,reviewerName,scheduledAt:scheduledAt?new Date(scheduledAt).toISOString():null,room,interviewerNames:interviewers.split(",").map(x=>x.trim()).filter(Boolean),durationMinutes:row.assignment?.duration_minutes??20,mode:row.assignment?.mode??"offline"})});const data=await response.json();if(!response.ok){setMessage(data.error??"시간 배정 실패");return;}setMessage(`${row.applicant_code} 면접 시간을 저장했습니다.`);await load();}
 async function archive(type:"interview_final"|"full_final"){const includePersonalData=confirm("개인정보를 포함한 장기보관용 ZIP을 생성할까요?\n확인: 개인정보 포함 / 취소: 비식별 아카이브");const response=await fetch(`/api/archive/${type}`,{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({recruitmentId,reviewerId,reviewerName,includePersonalData})});if(!response.ok){const data=await response.json();setMessage(data.error??"아카이브 생성 실패");return;}const blob=await response.blob();const link=document.createElement("a");link.href=URL.createObjectURL(blob);link.download=`coffeeright-${type}-${new Date().toISOString().slice(0,10)}.zip`;link.click();URL.revokeObjectURL(link.href);}
 return <main><header className="page-head"><div><p className="eyebrow">COFFEERIGHT · 면접 운영</p><h1>면접 대상자</h1><p className="muted">{reviewerName} · 대상 {rows.length}명</p></div><div className="head-actions"><a className="quiet-link" href="/applicants">서류평가</a><a className="quiet-link" href="/hermes">Hermes 가져오기</a><button className="secondary" onClick={()=>archive("interview_final")}>면접 종료 ZIP</button><button className="secondary" onClick={()=>archive("full_final")}>전체 최종 ZIP</button></div></header><div className="filter-row"><button className={filter==="all"?"filter active":"filter"} onClick={()=>setFilter("all")}>전체</button><button className={filter==="unscheduled"?"filter active":"filter"} onClick={()=>setFilter("unscheduled")}>시간 미배정</button><button className={filter==="shortage"?"filter active":"filter"} onClick={()=>setFilter("shortage")}>평가 부족</button><button className={filter==="variance"?"filter active":"filter"} onClick={()=>setFilter("variance")}>편차 경고</button></div>{message&&<p className="save-message">{message}</p>}{loading?<div className="empty">면접 현황을 불러오는 중입니다.</div>:<div className="interview-list">{visible.map(row=><InterviewRow key={row.id} row={row} save={saveSchedule}/>)}</div>}</main>
}

function InterviewRow({row,save}:{row:Row;save:(row:Row,time:string,room:string,interviewers:string)=>Promise<void>}){const [time,setTime]=useState(localInput(row.assignment?.scheduled_at??null));const [room,setRoom]=useState(row.assignment?.room??"");const [interviewers,setInterviewers]=useState((row.assignment?.interviewer_names??[]).join(", "));return <article className="interview-row"><div className="interview-main"><a href={`/interviews/${row.id}`}><strong>{row.applicant_code} · {row.name}</strong></a><span className="muted small">{row.major??"전공 미입력"} · 가능 시간 {row.interview_availability??"미입력"}</span><div className="badge-row"><span className={row.hermes_ready?"badge good":"badge warn"}>{row.hermes_ready?"Hermes 완료":"Hermes 미입력"}</span><span className={row.review_shortage?"badge warn":"badge good"}>평가 {row.review_count}/{row.minimum_review_count}</span>{row.interview_average!=null&&<span className="badge">평균 {row.interview_average.toFixed(2)}</span>}{row.high_variance&&<span className="badge warn">편차 {row.interview_min?.toFixed(2)}–{row.interview_max?.toFixed(2)}</span>}</div></div><div className="schedule-grid"><input className="text-input" type="datetime-local" value={time} onChange={e=>setTime(e.target.value)}/><input className="text-input" value={room} onChange={e=>setRoom(e.target.value)} placeholder="장소/링크"/><input className="text-input" value={interviewers} onChange={e=>setInterviewers(e.target.value)} placeholder="면접관, 쉼표 구분"/><button onClick={()=>save(row,time,room,interviewers)}>시간 배정</button></div></article>}
