"use client";
import { useState } from "react";
import Papa from "papaparse";

type Preview={valid:Array<{applicant_code:string;application_summary:string;recommended_questions:string[]}>;errors:string[];missing:string[];canCommit:boolean};

export default function HermesImportClient(){
 const [rows,setRows]=useState<Record<string,unknown>[]>([]); const [preview,setPreview]=useState<Preview|null>(null); const [message,setMessage]=useState(""); const recruitmentId=process.env.NEXT_PUBLIC_RECRUITMENT_ID??"";
 async function read(file:File){setMessage("");setPreview(null);const text=await file.text();try{if(file.name.toLowerCase().endsWith(".json")){const parsed:unknown=JSON.parse(text);setRows(Array.isArray(parsed)?parsed as Record<string,unknown>[]:(parsed as {rows?:Record<string,unknown>[]}).rows??[]);}else{const parsed=Papa.parse<Record<string,unknown>>(text,{header:true,skipEmptyLines:true});if(parsed.errors.length)throw new Error(parsed.errors[0].message);setRows(parsed.data);} }catch(e){setRows([]);setMessage(e instanceof Error?e.message:"파일을 읽지 못했습니다.");}}
 async function submit(action:"preview"|"commit"){const reviewerId=localStorage.getItem("coffeeright.reviewerId");const reviewerName=localStorage.getItem("coffeeright.reviewerName");const response=await fetch("/api/import/hermes",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,rows,recruitmentId,reviewerId,reviewerName})});const data=await response.json();if(!response.ok){setPreview(data);setMessage(data.error??"가져오기 실패");return;}if(action==="preview"){setPreview(data);setMessage(`검증 완료: ${data.valid.length}명`);}else{setMessage(`${data.imported}명의 Hermes 결과를 저장했습니다.`);setPreview(null);}}
 return <main className="narrow"><div className="review-top"><a className="quiet-link" href="/interviews">← 면접 대상 목록</a><span className="muted">Hermes 일괄 처리</span></div><h1>Hermes 결과 가져오기</h1><p className="lead">지원자 코드, 지원서 요약, 추천 질문을 JSON 또는 CSV로 가져옵니다. 지원자 코드로만 연결하며 가져오기 전에 누락·중복·미존재 코드를 검증합니다.</p><section className="card form-stack"><label className="field-label">결과 파일</label><input type="file" accept=".json,.csv,text/csv,application/json" onChange={e=>e.target.files?.[0]&&read(e.target.files[0])}/><p className="hint">필수 열: applicant_code, application_summary, recommended_questions. CSV의 질문 여러 개는 줄바꿈 또는 | 로 구분할 수 있습니다.</p><div className="row"><button disabled={!rows.length} onClick={()=>submit("preview")}>가져오기 전 검증</button>{preview?.canCommit&&<button className="secondary" onClick={()=>submit("commit")}>검증된 {preview.valid.length}명 저장</button>}</div>{message&&<p className="save-message">{message}</p>}</section>{preview&&<section className="card"><h2>검증 결과</h2><p>정상 {preview.valid.length}명 · 오류 {preview.errors.length}건 · 파일에 없는 면접 대상 {preview.missing.length}명</p>{preview.errors.length>0&&<ul className="error-list">{preview.errors.map(error=><li key={error}>{error}</li>)}</ul>}{preview.missing.length>0&&<p className="hint">누락 코드: {preview.missing.join(", ")}</p>}</section>}</main>
}
